### ISSUE TITLE
Can't send notifications through devicehive-cloud in WS mode

### ISSUE THREAD

**Issue by turistua** [devicehive/IoT-framework#11]
While trying to start cpu-stats.go example, it works only with cloud in REST mode.

**Comment by demon-xxi** [comment]
@Pilatuz, I double this request. 
The issue here not with notifications but with the fact that device is not created in WS mode as you probably know. I saw commit 33837b011b1e13c57363bc1f09ffe0c49f15045f that should fix this by passing AccessKey for WS. But as I know server side is not accepting it yet. 
Let's keep this open until server is updated.
Related to devicehive/devicehive-java-server#116

**Comment by Pilatuz** [comment]
As a temporary workaround you can provide a DeviceKey along with the AccessKey. DeviceKey is still required for websocket.

**Comment by demon-xxi** [comment]
@Pilatuz, as I understand we can close this issue now, right?

**Comment by Pilatuz** [comment]
no device key will be required in coming new version of java server
